### ISSUE TITLE
Problems when responding a request

### ISSUE THREAD

**Issue by taten14** [SystemRage/py-kms#10]
Im running server with python3.

SO Hosting Scritpt: Ubuntu18.04 Server

Error: ValueError: badly formed hexadecimal UUID string

SO asking KMS response: Windows10 Pro

pip3 packages:

asn1crypto (0.24.0)
attrs (17.4.0)
Automat (0.6.0)
blinker (1.4)
certifi (2018.1.18)
chardet (3.0.4)
click (6.7)
cloud-init (18.2)
colorama (0.3.7)
command-not-found (0.3)
configobj (5.0.6)
constantly (15.1.0)
cryptography (2.1.4)
distro-info (0.18)
httplib2 (0.9.2)
hyperlink (17.3.1)
idna (2.6)
incremental (16.10.1)
Jinja2 (2.10)
jsonpatch (1.16)
jsonpointer (1.10)
jsonschema (2.6.0)
keyring (10.6.0)
keyrings.alt (3.0)
language-selector (0.1)
MarkupSafe (1.0)
oauthlib (2.0.6)
PAM (0.4.2)
pip (9.0.1)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
pycrypto (2.6.1)
pygobject (3.26.1)
PyJWT (1.5.3)
pyOpenSSL (17.5.0)
pyserial (3.4)
python-apt (1.6.2)
python-debian (0.1.32)
pytz (2018.7)
pyxdg (0.25)
PyYAML (3.12)
requests (2.18.4)
requests-unixsocket (0.1.5)
SecretStorage (2.3.1)
service-identity (16.0.0)
setuptools (39.0.1)
six (1.11.0)
ssh-import-id (5.7)
systemd-python (234)
Twisted (17.9.0)
tzlocal (1.5.1)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.22)
wheel (0.30.0)
zope.interface (4.3.2)

**Execution:**

$ python3 server.py

Client sending
===============>                Server received RPC Bind Request !!!
                                Server parsing RPC Bind Request...
                                Server generating RPC Bind Response...
Client receiving
<===============                Server sending RPC Bind Response...
                                RPC Bind acknowledged !!!

Client sending
===============>                Server received RPC Activation Request !!!
                                Server parsing RPC Activation Request...
                                Server processing KMS Activation Request...
----------------------------------------
Exception happened during processing of request from ('192.168.21.241', 49859)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "server.py", line 157, in handle
    res = str(handler.populate()).encode('latin-1')
  File "/home/administrator/py-kms/py3-kms/rpcBase.py", line 42, in populate
    return self.generateResponse(self.parseRequest())
  File "/home/administrator/py-kms/py3-kms/rpcRequest.py", line 22, in generateResponse
    responseData = kmsBase.generateKmsResponseData(request['pduData'], self.config)
  File "/home/administrator/py-kms/py3-kms/kmsBase.py", line 327, in generateKmsResponseData
    return messagehandler.executeRequestLogic()
  File "/home/administrator/py-kms/py3-kms/kmsRequestV5.py", line 71, in executeRequestLogic
    responseBuffer = self.serverLogic(decrypted['request'])
  File "/home/administrator/py-kms/py3-kms/kmsBase.py", line 188, in serverLogic
    if uuid.UUID(skuitem['Id']) == skuId:
  File "/usr/lib/python3.6/uuid.py", line 140, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
----------------------------------------

**Comment by SystemRage** [comment]
Ooops I messied KmsDataBase.xml.
Now should work.
