### ISSUE TITLE
Windows 2019 Datacenter Activation Error

### ISSUE THREAD

**Issue by rezafathikohi** [SystemRage/py-kms#105]
Hello,

when I want to activate the windows 2019 Datacenter, the attached error will appear. what is the problem?

![kms](https://user-images.githubusercontent.com/24651863/95705701-c1570a00-0c61-11eb-9f43-9fb902dbd3ab.jpg)

**Comment by SystemRage** [comment]
Maybe....
disable firewall or create exception port 1688.

**Comment by rezafathikohi** [comment]
It works fine with other versions of windows but with this version shows the above error.

**Comment by SystemRage** [comment]
See #112.
correctly updates ? miss some KB package ?

**Comment by rezafathikohi** [comment]
After updating the windows it activated
