### ISSUE TITLE
Office 2019 not working

### ISSUE THREAD

**Issue by DoyunShin** [SystemRage/py-kms#109]
when i unpkey and inpkey,

> PS C:\Program Files (x86)\Microsoft Office\Office16> cscript //nologo ospp.vbs /inpkey:6NWWJ-YQWMR-QKGCB-6TMB3-9D9HK
> ---Processing--------------------------
> ---------------------------------------
> ERROR CODE: 0xC004F069
> ERROR DESCRIPTION: The Software Licensing Service reported that the product SKU is not found.
> ---------------------------------------
> ---Exiting-----------------------------

![image](https://user-images.githubusercontent.com/60532811/96679098-f96ef300-13ad-11eb-9cca-c5a2d1a2f152.png)

There has errorcode

I installed Office 2019 Professional Pro edition

**Comment by Simonmicro** [comment]
Did you made sure to install a Volume-Licensed Version of Office? The retail one does not include the needed KMS features. Did you even read the wiki article for this?

> Note that you’ll have to install a volume license (VL) version of Office. Office versions downloaded from MSDN and / or Technet are non-VL.

**Comment by DoyunShin** [comment]
oh i see
ty

**Comment by Simonmicro** [comment]
No problem :grin:
