### ISSUE TITLE
Windows 10 pro 1903 activation Error

### ISSUE THREAD

**Issue by rezafathikohi** [SystemRage/py-kms#110]
Hello

When I want to activated the windows 10 pro I get this error message. What is the problem?

![image](https://user-images.githubusercontent.com/24651863/97349964-5e8e8100-18a5-11eb-9b31-31b3f915753e.jpeg)

**Comment by SystemRage** [comment]
See #112.
however i think you changed  the hardware (motherboard or other) and your HWID is imprinted to another thing.
You have to login with your MS account and reactivate.
Or you have to start all over starting with your initial version, following this trick (MDL forums):
`
1. Validate your w7 SP1 (W8.1) online, best using IE.
2. Generate a genuine ticket of your installation by:
2.1 Copy gatherosstate.exe from your downloaded Windows 10 10240 ISO to your installation which should be upgraded.
2.2 Run it on your activated and validated Windows. It'll output GenuineTicket.xml. Save this on a USB thumb drive or something.
2.3 Then do a fresh install with your suitable w10 ISO, skip to enter key at setup procedure.
2.4 Once it's installed make sure your internet connection is DISABLED/do not enable the internet connection! Reboot w10.
2.5. Copy GenuineTicket.xml to C:\programdata\microsoft\windows\clipsvc\genuineticket\ of your w10 installation and reboot again.
2.6. Connect online, it should activate.
`

**Comment by rezafathikohi** [comment]
Activated with getting new updates
