### ISSUE TITLE
Windows 10 Pro 2004 Activation Error: 0xC004F074

### ISSUE THREAD

**Issue by lucaloiacono** [SystemRage/py-kms#111]
Hello,

whenever i try to activate a machine running Windows 10 Pro (v. 2004) i get this error:
`Error: 0xC004F074 The Software Licensing Service reported that the computer could not be activated. No Key Management Service (KMS) could be contacted. Please see the Application Event Log for additional information.`

Firewall is open and time is synced correctly.

I don't know if the problem is related to Windows version but i have no issue with other PCs running Windows 10 Pro v. 1903.

Do you have any hint?

**Comment by SystemRage** [comment]
See #112.
usually this error comes from antivirus that blocks request/response transmission.
https://py-kms.readthedocs.io/en/latest/Usage.html#activation-procedure (4) - (5)
You said that firewall is open, so... ????.

**Comment by lucaloiacono** [comment]
Just realised the KMS server address did not change, even after launching `slmgr.vbs -skms {address}`
Found a way to "force" it, now it's working great.

Thank you for your help!
