### ISSUE TITLE
Implement brief troubleshooting docs

### ISSUE THREAD

**Issue by SystemRage** [SystemRage/py-kms#112]
Some questions you may not have asked yourself:
- Are you activating a Windows legit copy checked with sha256, md5 or is a warez torrent version ?
- Is a clean installation (format all) ? You skipped inserting any key during installation, 
turning off internet connection, first activating and then updating Windows (and eventually later upgrading)?
- Have you installed all latest packages ? especially before upgrading ? Are you upgrading using "Update Assistant" tool 
to switch from Windows 7 / 8 / 8.1 to 10 (for me has always worked) ?
- If isn't a clean install, so far as you have kept activated your Windows copy ? Have you used some other activator (maybe not trusted) that
inject or change .dll and may have corrupt something ?
- Have you forgot to reactivate at least once before 180 (45 or 30, depending on your version) days ?
- Is your system very tweaked with some service disabled ?
- Have you disabled (or created an exception for) ALL firewalls / antivirus (Windows defender, etc..), server-side AND client-side ?
- If you have already activated with a OEM/Retail/Any Other license and now you want to activate using py-kms, 
have you switched to volume channel with appropriate gvlk ? Deleting first your previous key (example: https://github.com/SystemRage/py-kms/issues/24#issuecomment-492431436) ?
- Are you running commands opening the elevated command prompt ?
- Are you connecting correctly to your emulated server ?
- Have you tried to fix with Windows Troubleshoot, sfc /scannow or other strange Windows tools ?
- If you activated successfully with py-kms other Windows stuff, don't consider could be an 
error specific for your PC (so you need a scented clean installation) ?

If you have already thought about this, your last hope is to solve your problem
reading some verse of the Holy Bible of activations: "MDL forums";
otherwise "I don't know !" :)

**Comment by Simonmicro** [comment]
* Is your `py-kms` really running? Already tried to enable debug logs?
* Did you already searched for your issue here?
* Are you running the latest version of `py-kms`?
* Office: Did you made sure to use a Office **with** GLVK support?!
* You found a real bug? Could you maybe make our life's easier and describe what goes wrong **and** also provide some information about your environment (OS, Python-Version, Docker, Commit-Hashes, Network-Setup)?
* When you post logs: Please remove personal information (replace IPs with something like `[IP_ADDRESS_A]`)...

**Comment by Simonmicro** [comment]
@SystemRage Do you plan to extend the wiki yourself (I think adding this would really help), or should I set it onto my queue to be done in the next weeks?

**Comment by SystemRage** [comment]
If you can create one of your excellent PR would be great
