### ISSUE TITLE
Update pykms on docker

### ISSUE THREAD

**Issue by rezafathikohi** [SystemRage/py-kms#114]
I installed pykms on docker as you described in the wiki. So if there is a new update , how can I update the py server in docker?

**Comment by Simonmicro** [comment]
# Automatically

Use watchtower - as noted in the docs. It will pull & restart the container by itself.

# Manually

Hmmm...

1. `docker stop py-kms`
2. `docker pull pykmsorg/py-kms`
3. Rerun your docker execution command you used before...

# With compose

1. `docker-compose pull`
2. `docker-compose up -d`

I hope that helps...

**Comment by rezafathikohi** [comment]
Is this the command?

$ docker run -d \
    --name watchtower \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower

**Comment by Simonmicro** [comment]
> Is this the command?
> 
> $ docker run -d
> --name watchtower
> -v /var/run/docker.sock:/var/run/docker.sock
> containrrr/watchtower

That should do it. You'll then have to containers running - one py-kms and one watchtower, which checks every 5 minutes for new images over on Docker Hub. Do you think I should add this to the docker-compose file section? Then you would only need one command and you are done.

**Comment by rezafathikohi** [comment]
Yes definately
