### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by rezafathikohi** [SystemRage/py-kms#117]
Is there any GUI in docker? Because i want to see which computers are connecting and getting the license.

**Comment by Simonmicro** [comment]
Nope, no way. Your only chance is to get the database file and open it (it is a sqlite database). Or you program it yourself (with something like flask). Sorry, but Docker is build that way :)

**Comment by rezafathikohi** [comment]
Where are these sqlite files located?

**Comment by Simonmicro** [comment]
You can specify that (https://py-kms.readthedocs.io/en/latest/Usage.html#docker-environment) - use the Docker container with the `python3` tag and mount a folder to get the db files out of the image. For that you are on your own - but @SystemRage will be happy to accept any PR for the docs, when you wish to extend our guides.
