### ISSUE TITLE
Windows 10 20H2

### ISSUE THREAD

**Issue by vlad666** [SystemRage/py-kms#120]
Can't activate windows 10 20H2

**Comment by Simonmicro** [comment]
Give us at least _something_.

Try this BEFORE opening such an "informational-packed" issue: https://py-kms.readthedocs.io/en/latest/Troubleshooting.html

**Comment by dogtopus** [comment]
I'm running 20H2 and py-kms works fine for me.

Please post details about your setup so people who wish to help can take a look.

**Comment by thatsysadmin** [comment]
Can confirm. Works fine.

**Comment by simonmicro** [comment]
Btw - I can also confirm it works! Tested with more than 20 systems, sooo... @SystemRage could you close this?

**Comment by agentechirimoyo** [comment]
All ok, thanks!!
