### ISSUE TITLE
Docker run it is not working with python3 tag

### ISSUE THREAD

**Issue by xueshiji** [SystemRage/py-kms#124]
I run it using docker with command:
"docker run -d --name py3-kms -p 8080:8080 -p 1688:1688 -e IP=0.0.0.0 -e PORT=1688 -e SQLITE=true --restart always ykmsorg/py-kms:python3".
Then the container will crash and restart ,and crash and restart...

**Comment by wulfftech** [comment]
Try changing SQLITE=true to SQLITE=false
