### ISSUE TITLE
Error: ←[7m←[91m←[1mSO_REUSEPORT not supported on this platform. Exiting...←[0m

### ISSUE THREAD

**Issue by ganeshkakade** [SystemRage/py-kms#126]
when I tried to run the pykms_Server.py, got the error "←[7m←[91m←[1mSO_REUSEPORT not supported on this platform. Exiting...←[0m"
Any idea what could be the issue? Is there a thing that I need to enable in the system first before running the given command?

Configuration: 
Edition	    : Windows 10 Pro
Version	    : 20H2
OS build	    : 19042.746
Experience   : Windows Feature Experience Pack 120.2212.551.0

**Comment by SystemRage** [comment]
try with: 
`python3 pykms_Server.py connect --no-reuse`

It seems Windows only knows the SO_REUSEADDR option, there is no SO_REUSEPORT.
#102

**Comment by ganeshkakade** [comment]
Awesome! Thanks @SystemRage. Now it is working.
