### ISSUE TITLE
What does the "connect" subparameter do?

### ISSUE THREAD

**Issue by Xtendera** [SystemRage/py-kms#127]
I was getting an error while running this in windows. I had to run "python pykms_Server.py connect -no-reuse" instead of just "python pykms_Server.py" What is the difference? In the docs, they don't talk much about the "connect" parameter.

Thank You!

**Comment by SystemRage** [comment]
https://github.com/SystemRage/py-kms/blob/master/docs/Usage.md#subparser-connect
