### ISSUE TITLE
If yoy dont like russia

### ISSUE THREAD

**Issue by ghost** [SystemRage/py-kms#135]

**Comment by 6ec123321** [comment]
Бля, гандоны и пидоры, если вам Русские люди не нравятся, но вы упыри и вам не дают бабы - идите нахер, вы говно.

**Comment by 6ec123321** [comment]
Your wife make cum with me )))

**Comment by simonmicro** [comment]
HEY! THIS IS ENOUGH! Please delete this issue and think about what you are doing! This platform is not the place to write about such stuff... At least not this repository!

**Comment by 6ec123321** [comment]
Удалено, чё хотел ?

**Comment by 6ec123321** [comment]
..............Я сходил включил все, еще раз сука нарисуешься, тебя порежут

**Comment by 6ec123321** [comment]
понял ?

**Comment by 6ec123321** [comment]
еще раз ивижу ваших - убью, вы поняли ?
