### ISSUE TITLE
I'm afraid I don't get it

### ISSUE THREAD

**Issue by Nickduino** [SystemRage/py-kms#14]
I'm supposed to use a serial key on my Office/Windows install and tell it to go check the licence on the Raspberry Pi running on my local network, right?

Could the documentation be a bit more exhaustive?

**Comment by SystemRage** [comment]
Add a firewall rule, then run the server:
```user@user ~/path/to/folder/py-kms $ python server.py```
Finally (client-side) use this steps:
https://github.com/SystemRage/py-kms/wiki/Manual#activation-procedure

**Comment by Nickduino** [comment]
Thanks!
