### ISSUE TITLE
About py-kms security

### ISSUE THREAD

**Issue by phrasjong** [SystemRage/py-kms#15]
what about this program sercurity? It can defense hacker‘s atack?

**Comment by 6ec123321** [comment]
It is safe if you do not publish a service on the Internet, only a local network or VPN xD)

**Comment by elekgeek** [comment]
the real question is how safe MS KMS service is :- /

**Comment by phrasjong** [comment]
I found sometimes the kms active response dosn't active the windows system, and i try more than one, maybe five times, it just active the windwos system, I really doubt that active response is always can active the windwos system...

**Comment by 6ec123321** [comment]
> I found sometimes the kms active response dosn't active the windows system, and i try more than one, maybe five times, it just active the windwos system, I really doubt that active response is always can active the windows system...

What Windows OS Version ?

**Comment by 6ec123321** [comment]
I tested on 2008 / 2008R2 Standard / Enterprise x64, Windows 7 Professional with Service Pack 1 x32 / x64, MS Office 2010 Standard / Professional x32 / x64. Other versions have not yet tested.

Productive stand:
[Asus RTN-15U](https://www.asus.com/Networking/RTN15U/specifications/)
[TomatoUSB by Shibby K26USB-1.28.RT-N5x-MIPSR2-140-miniVPN](http://tomato.groov.pl/download/K26RT-N/build5x-140-MultiWAN/Asus%20RT-Nxx/tomato-K26USB-1.28.RT-N5x-MIPSR2-140-miniVPN.zip)
[Entware-NG](http://entware.zyxmon.org/binaries/mipsel/installer/installer.sh)
[Python 2.7.14](http://entware.zyxmon.org/binaries/mipsel/python_2.7.14-5_mipselsf.ipk)
**py2-kms**

**Comment by phrasjong** [comment]
Windows OS Version : Windows 7 Professional 64. 
I have a lot of virtual machine(30-60) run this OS, and not every time it doesn't work, just low probability of occurrence with 1-3 machine doesn't actived at first time, this active is used Windows boot task. And I convinced the network is already ready. Until attempts to activate multiple times to succeed.

**Comment by 6ec123321** [comment]
> Windows OS Version : Windows 7 Professional 64.
> I have a lot of virtual machine(30-60) run this OS, and not every time it doesn't work, just low probability of occurrence with 1-3 machine doesn't actived at first time, this active is used Windows boot task. And I convinced the network is already ready. Until attempts to activate multiple times to succeed.

Developers have released hotfixes KB4480960 and KB4480970 for Windows 7 SP1 and Windows Server 2008 R2 SP1. They work in the operating system. System users have various errors, including KMS, Not Genuine and 0xc004f200 activation errors.

Check the list of installed updates
