### ISSUE TITLE
Log to STDOUT

### ISSUE THREAD

**Issue by adrianmace** [SystemRage/py-kms#22]
Hi there,

Firstly I want to thank you for this diagnostic tool. We are using it to test the user experience of upgrading a few clients to KMS-based activations in our test lab before contacting MS and going through the hoops.

It would be great if you could log requests/results to STDOUT so that the docker container (supermarcus/pykms-docker is the one I'm using) can accurately log information? Simple log format of [time] - [ip / hostname] - [status of requested/activated] - [product (if available)] would be ideal!

I am checkpointing the VMs before and after the activation process, but it would be nice to just see which IPs are requesting / activating so I can go through and deactivate these quickly.

**Comment by SystemRage** [comment]
maybe i don't fully understand your format but,
try new version with:
```python3 pykms_Server.py -F STDOUT -V MINI```
