### ISSUE TITLE
0x8007000D Error

### ISSUE THREAD

**Issue by testcaoy7** [SystemRage/py-kms#23]
I have tried both python2 and python3 under Windows. I ran "python server.py 127.0.0.1" and tried to activate Windows. However, Windows can not be activated. It will throw a 0x8007000D error. The py-kms I used is the latest git version.

The problem only persists when running server.py under Windows version of python. I ran py-kms under Linux and Windows can be successfully activated when the KMS server is pointed to the Linux machine.

**Comment by testcaoy7** [comment]
This error persists in Windows 10. The version I used is Windows 10 Enterprise v1903.
I also tried using py-kms under Windows 7 and Windows 7 Enterprise can be activated via 127.0.0.1.

**Comment by testcaoy7** [comment]
I can confirm that another KMS emulator, vlmcsd also have the same issue.
Maybe the problem belongs to Windows 10 instead of KMS emulator.

**Comment by thewinner666** [comment]
That is because it is made that way. In order to activate a Windows machine you MUST start server.py on a seperate machine, not on the same.

**Comment by SystemRage** [comment]
I think the problem is "auto-activation" (py-kms / vlmcsd server running on the same PC that should be activated).
Starting from Windows 8 (or maybe Windows 8.1) server and client must be two distinct PCs / devices.
See:
https://github.com/Wind4/vlmcsd/issues/6
https://github.com/Wind4/vlmcsd/issues/9

**Comment by firefinchdev** [comment]
I used WSL2 to start the server and it worked

**Comment by ganeshkakade** [comment]
@firefinchdev Do you mean you have used WSL2 on the same machine or did you use two different machine to achieve activation?

**Comment by firefinchdev** [comment]
> @firefinchdev Do you mean you have used WSL2 on the same machine or did you use two different machine to achieve activation? 

I used WSL2 on the same machine.

**Comment by ganeshkakade** [comment]
> > @firefinchdev Do you mean you have used WSL2 on the same machine or did you use two different machine to achieve activation?
> 
> I used WSL2 on the same machine.

Thanks @firefinchdev . Now the issue is resolved

**Comment by firefinchdev** [comment]
> > > @firefinchdev Do you mean you have used WSL2 on the same machine or did you use two different machine to achieve activation?
> > 
> > I used WSL2 on the same machine.
> 
> Thanks @firefinchdev . Now the issue is resolved

Resolved using WSL2 on same machine?

**Comment by ganeshkakade** [comment]
> > > > @firefinchdev Do you mean you have used WSL2 on the same machine or did you use two different machine to achieve activation?
> > > 
> > > 
> > > I used WSL2 on the same machine.
> > 
> > 
> > Thanks @firefinchdev . Now the issue is resolved
> 
> Resolved using WSL2 on same machine?

Yes, used WSL2 on the same machine (hosted pykms_Server.py code as service on linux kernel) and used windows as client
