### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by speedst3r** [SystemRage/py-kms#27]
Commit 750713d has introduced an error in pykms_Misc.py:

```
Traceback (most recent call last):

  File "pykms_Server.py", line 23, in <module>
    import pykms_RpcBind, pykms_RpcRequest
  File "/home/py-kms/py-kms/pykms_RpcRequest.py", line 6, in <module>
    import pykms_Base
  File "/home/py-kms/py-kms/pykms_Base.py", line 238, in <module>
    import pykms_RequestV4, pykms_RequestV5, pykms_RequestV6, pykms_RequestUnknown
  File "/home/py-kms/py-kms/pykms_RequestUnknown.py", line 6, in <module>
    from pykms_Misc import ErrorCodes
  File "/home/py-kms/py-kms/pykms_Misc.py", line 88
    except AttributeError:
                         ^
TabError: inconsistent use of tabs and spaces in indentation
```
Committer has used spaces to indent lines 87-90 whilst the rest of the file uses tab indentation.

**Comment by SystemRage** [comment]
OK.

**Comment by speedst3r** [comment]
Thanks. I notice you are make changes and commits through the web interface.

It may be better to clone your repo locally, make changes, test etc. then push back up to github. Something like this would have been picked up that way (or not occurred in the first place).

**Comment by SystemRage** [comment]
Yes it's true, i used github web interface (not complete as git commands).
Now i'm learning some git commands to do things well.
