### ISSUE TITLE
Add support for Windows 10 1903

### ISSUE THREAD

**Issue by baMain** [SystemRage/py-kms#29]
Hi,
I saw that Windows 10 1903 was released today, and so there is a need to update "KmsDataBase.xml".

How can one update the "KmsDataBase.xml" file? from where can we get the values?

**Comment by elekgeek** [comment]
did you try to activate it and failed? Because when I was able to activate Windows 10 1903..

**Comment by baMain** [comment]
I didn't try to activate it,
I only checked the xml file.

Will try soon

**Comment by SystemRage** [comment]
There is no need to update KmsDataBase.xml because 1903 is 
a Windows update and not a new product, so activation should work normally.
