### ISSUE TITLE
SQLite errors

### ISSUE THREAD

**Issue by speedst3r** [SystemRage/py-kms#31]
I came across a couple of errors running pykms_Server with SQLite - don't have the actual errors anymore but you could probably replicate them.

1. 'os' is not defined, pykms_Sql.py, line 17. - Added 'import os', [7e40ba6](https://github.com/speedst3r/py-kms/commit/7e40ba63ff1db9e7b264b111f2d4f93eed38ab17)
2. 'self' is not defined, pykms_Sql.py line 78. - removed 'self' from the connection reference, [5441771](https://github.com/speedst3r/py-kms/commit/544177184363554054fdc41583979e1b6df52829)

**Comment by speedst3r** [comment]
Command line to launch py-kms:
```
/usr/bin/python3 pykms_Server.py 0.0.0.0 1688 -l 1033 -c 26 -a 120 -r 10080 -s -w RANDOM -V INFO -F /var/log/pykms_server.log
```

**Comment by elekgeek** [comment]
thanks for the command, but there is a couple of errors in the code, in file pykms_Sql.py as follows:

add "import os" at the beginning of this file, right after #!/usr/bin/env python3
and at line 78, modify:
con = sqlite3.connect(self.dbName)
to
con = sqlite3.connect(dbName)

this should solve your issue.

**Comment by speedst3r** [comment]
Yeah - it's my PR (#32) with these fixes, before taking it out of draft I wanted it confirmed that it was an issue and not something in my environment.

**Comment by elekgeek** [comment]
sorry man, I did not read your first [msg ](https://github.com/SystemRage/py-kms/issues/31?_pjax=%23js-repo-pjax-container#issue-446971990)and thought you were looking for the solution, my bad..

Any way, I tested it with office 2019 and it works ok with the fix :)

**Comment by speedst3r** [comment]
No worries. I have a CI pipeline that builds a Docker image, currently the Dockerfile is using my fork, once the PR is merged I can submit a PR for my updated Dockerfile and start.sh, and can revert to using the upstream repo :)

**Comment by SystemRage** [comment]
Many thanks for debug and contributing.
