### ISSUE TITLE
No IPv6 support

### ISSUE THREAD

**Issue by vosdev** [SystemRage/py-kms#36]
Server.py breaks if you use a IPv6 only hostname (Only an AAAA record, no A record) or `::` instead of `0.0.0.0`

```
# python3 pykms_Server.py :: 1688          
Exception in thread Thread-1: 
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "pykms_Server.py", line 51, in run
    self.server = server_create()
  File "pykms_Server.py", line 181, in server_create
    server = socketserver.TCPServer((srv_config['ip'], srv_config['port']), kmsServer)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno -9] Address family for hostname not supported
```

**Comment by Nachtmerrie** [comment]
I worked around the issue by running the server in a docker container, but I found some bugs with the start.sh script that I will make a PR for soon.

**Comment by FredBaker** [comment]
I took a look at threads.py line 51. It looks like you're opening an IPv4-only socket. Your need one that is capable of either address family, or you need a thread for each address (family?) in question.

**Comment by Simonmicro** [comment]
@vosdev Any progress on this? If not, I'll try to update it to a IPv6 socket in the next days by myself. And yes, Docker is always the better choice :laughing:.

**Comment by vosdev** [comment]
@Simonmicro no I have not tried to rewrite the code :) I have it running inside a docker container and the docker-proxy takes care of the v6 socket for me. I would prefer to have a native v6 socket so that I can actually see the requests in the logs instead of the docker0 bridge IP.

**Comment by Simonmicro** [comment]
Okay, PR is pending. It should even work on a ipv4-only-system, because the Linux kernel maps the ips.
