### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by vosdev** [SystemRage/py-kms#38]
```
   PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
 32911 root       20   0 40608 19624  8136 S 100.  0.2  2:07.29 /usr/bin/python3 pykms_Server.py 0.0.0.0 1688 -l 1033 -c 26 -a 120 -r 10080 -w 364F463A8863D35F -V ERROR
 32925 root       20   0 40608 19624  8136 R 100.  0.2  2:06.50 /usr/bin/python3 pykms_Server.py 0.0.0.0 1688 -l 1033 -c 26 -a 120 -r 10080 -w 364F463A8863D35F -V ERROR
```

constant 100% CPU usage..

**Comment by ackurdeeve** [comment]
me too...have to kill it to recover. I used it on GCP.

**Comment by SystemRage** [comment]
Mine.
![terminal](https://user-images.githubusercontent.com/25354386/59308249-d6540f80-8ca0-11e9-959f-8dacce2b413e.png)

**Comment by Nachtmerrie** [comment]
@SystemRage Can you start up the python3 docker container? That's how i am running it. On a fully up to date ubuntu 18.04, docker 18.09-6

I put LOGLEVEL=DEBUG but there is no logging at all

**Comment by darkstar** [comment]
Try this patch:

```diff
diff --git a/py-kms/pykms_Server.py b/py-kms/pykms_Server.py
index 80c182a..2a1638d 100644
--- a/py-kms/pykms_Server.py
+++ b/py-kms/pykms_Server.py
@@ -10,6 +10,7 @@ import logging
 import os
 import errno
 import threading
+import time

 try:
         # Python 2 import.
@@ -57,6 +58,7 @@ class server_thread(threading.Thread):
                                     self.is_running = False
                                     self.server = None
                             self.queue.task_done()
+                    time.sleep(0.1)

 ##-----------------------------------------------------------------------------------------------------------------------------------------------

@@ -249,6 +251,7 @@ class kmsServer(socketserver.BaseRequestHandler):
                                 loggersrv.info("Responded to activation request.")
                                 ShellMessage.Process([-3, 18, 19]).run()
                                 break
+                time.sleep(0.1)

         def finish(self):
                 self.request.close()
```

ZIP file:
[pykms-reduce-cpu.zip](https://github.com/SystemRage/py-kms/files/3301169/pykms-reduce-cpu.zip)

**Comment by Nachtmerrie** [comment]
Yeah that reduces the load for me. Ugly workaround but hey it works :)

**Comment by Nachtmerrie** [comment]
> 
> 
> Mine.
> ![terminal](https://user-images.githubusercontent.com/25354386/59308249-d6540f80-8ca0-11e9-959f-8dacce2b413e.png)

With the sleep in the while loop the 100% CPU usage is gone. Could you run the pykms_Server.py in a docker container?

**Comment by SystemRage** [comment]
I investigated problem and i noted that's dependent on how docker container is created.
So i created a docker container in this way:
![1](https://user-images.githubusercontent.com/25354386/60688137-9bb25100-9eb3-11e9-85eb-119d706523f0.png)
and visualized some things:
![2](https://user-images.githubusercontent.com/25354386/60688188-f3e95300-9eb3-11e9-8b54-0521cd176142.png)
Actually there's a cpu overload. (with commands ``` sudo docker stats --no-stream``` and  ``` sudo docker exec -ti pykmshighload top```)
![3](https://user-images.githubusercontent.com/25354386/60688202-05caf600-9eb4-11e9-9a6c-46107b3a7fa0.png)
Then i created another docker container with ```-it``` option, and this doesn't suffer the same problem.
(view previous image) and with  ```sudo docker exec -ti pykmslowload top```:
![4](https://user-images.githubusercontent.com/25354386/60688525-06648c00-9eb6-11e9-8738-2bebc9179af4.png)
With this commands i tested that py-kms process run good:
```
sudo docker exec -ti pykmslowload bash
python3 pykms_Client.py 0.0.0.0 1688
cat /var/log/py3-kms.log
sudo docker logs pykmslowload
```
Note: environment variables must be called before container, so run-py3-kms.sh, run-py2-kms.sh and docker readme require correction.

I await feedback.

**Comment by Nachtmerrie** [comment]
Seems to work pretty well 👍

**Comment by williamsmt** [comment]
I'm running master branch on a vanilla 18.04 install (not Docker-ized). Standard systemd unit file produces a 100% CPU utilization due to loop logic. Is this in pipeline to address, or is the best workaround to wrap in a screen -DmS shell?

[Unit]
Description=kms
After=network.target
Wants=network-online.target

[Service]
ExecStart=/usr/bin/python3 /opt/kms/py-kms/pykms_Server.py -V DEBUG --logfile /var/log/py-kms_server.log
Restart=always
KillMode=process
Type=idle
User=nobody
Group=nogroup

[Install]
WantedBy=multi-user.target

**Comment by Netzvamp** [comment]
> I'm running master branch on a vanilla Ubuntu 18.04 install (not Docker-ized). Standard systemd unit file produces a 100% CPU utilization due to loop logic. Is this in pipeline to address, or is the best workaround to wrap in a screen -DmS shell?
> 
> [Unit]
> Description=kms
> After=network.target
> Wants=network-online.target
> 
> [Service]
> ExecStart=/usr/bin/python3 /opt/kms/py-kms/pykms_Server.py -V DEBUG --logfile /var/log/py-kms_server.log
> Restart=always
> KillMode=process
> Type=idle
> User=nobody
> Group=nogroup
> 
> [Install]
> WantedBy=multi-user.target

I've the same issue. I think it's something about systemd, cause it always start 2 or more processes, but only one is needed (like in @SystemRage 's screenshot). I'll try to stop that, lets see what happens ...

**Comment by Netzvamp** [comment]
> I have the same issue and fixed it by reducing the load in the main busy-waiting loops.
> 
> Try this patch:
> 
> ```diff
> diff --git a/py-kms/pykms_Server.py b/py-kms/pykms_Server.py
> index 80c182a..2a1638d 100644
> --- a/py-kms/pykms_Server.py
> +++ b/py-kms/pykms_Server.py
> @@ -10,6 +10,7 @@ import logging
>  import os
>  import errno
>  import threading
> +import time
> 
>  try:
>          # Python 2 import.
> @@ -57,6 +58,7 @@ class server_thread(threading.Thread):
>                                      self.is_running = False
>                                      self.server = None
>                              self.queue.task_done()
> +                    time.sleep(0.1)
> 
>  ##-----------------------------------------------------------------------------------------------------------------------------------------------
> 
> @@ -249,6 +251,7 @@ class kmsServer(socketserver.BaseRequestHandler):
>                                  loggersrv.info("Responded to activation request.")
>                                  ShellMessage.Process([-3, 18, 19]).run()
>                                  break
> +                time.sleep(0.1)
> 
>          def finish(self):
>                  self.request.close()
> ```
> 
> ZIP file:
> [pykms-reduce-cpu.zip](https://github.com/SystemRage/py-kms/files/3301169/pykms-reduce-cpu.zip)

Valid fix, i guess.

**Comment by TCB13** [comment]
Also having this issue, the patch seems to work.

**Comment by SystemRage** [comment]
Adding some timeout when getting from queue resolves cpu overload (similar to sleep(), but more elegant). The second timeout (in request handler) can be omitted, tested without it and cpu stays low.
