### ISSUE TITLE
[PROPOSAL] Make docker integration better

### ISSUE THREAD

**Issue by Simonmicro** [SystemRage/py-kms#53]
I would like to see a better integration into docker. @SystemRage What do you think about following changes:
- [x] Create an "official" py-kms image at the docker hub (in that case it would be good when the projects owner creates an account and sets it up to auto-build the master using the docker hub infrastructure)
- [x] Update the README to mention the new docker hub image
- [ ] Add the new run command into the wiki (so it would use the official docker image from the hub)
- [ ] Add a little tutorial for the docker build process to the wiki
- [x] Maybe reference a project like Watchtower for docker to ensure that the py-kms image is always up to date
If @SystemRage approves this, I would happy to create the necessary merge requests and help at the realisation.

**Comment by SystemRage** [comment]
I'm not very familiar with docker so
feel free to create all you want, then i'll add your PRs.
Your work will be highly appreciated.

**Comment by Simonmicro** [comment]
@SystemRage Hi, that sounds really good! I already started to work on the required changes but now ran into an issue with docker hub. They require me to have the Ownership of the repo I configure the auto builds for (my fork it already works). Of course thats not possible! To still make this work I tested a workaround: I would like to ask you to create an own account on the docker hub and create a new Organisation. Then link your GitHub account to this Organisation (make sure to select limited access, so docker only sees your public projects). After that you can (temporarly) add me, so i can create the image and configure the builds using your GitHub repo. If you give me permanent access i would happy to maintain the official inages indefinitvly. Alternativly I cloud type you a little guide, how I would set it up - so you wouldn't have to work with me 😃.
You can already check my work in my fork and determine wether you would like that or not.
If you have _any_ qeuestions regarding this procedure feel free to ask them - I would be happy to assist you!

**Comment by Simonmicro** [comment]
@SystemRage I would like to update the wiki, but I can't find any edit button (like over on GitLab). Could you assist me on that?

**Comment by Simonmicro** [comment]
Okay, since I'm not able to update the wiki, I call this issue closed.
Feel free to experiment and work with docker - I'll be here to help :grinning: 
See you!

**Comment by SystemRage** [comment]
If you still want i added wiki files as markdown so you can create PRs on it.
Then i update manually py-kms.wiki.git

**Comment by Simonmicro** [comment]
@SystemRage What would you think about an other approach? In the last days i started to work with Hugo (and really like it) - it is also able to generate an static site from Markdown files. With this a new doc folder would be needed inside the repo. Also an other repo to git push the static files to... Maybe a little bit too complicated - [demo](https://themes.gohugo.io/theme/hugo-book/)...

**OR**

...maybe Sphinx? I don't have too much experience with it, but I guess they both work very similar. Sphinx also is used for readthedocs - and I think that would be a great addition to this project! [Demo](https://packaging.python.org/)

In any way: With this new approach any user is able to receive a copy of the wiki inside the repo folder AND they can directly commit to it. This way you don't need to update the wiki manually.

As always: Because I want to learn this anyways I offer my help - if you approve this I would start a new PR to implement this. Maybe I'll need your help for the Sphinx integration - we'll see.

**Comment by SystemRage** [comment]
Certainly, go ahead.

**Comment by Simonmicro** [comment]
Superseeded by #82
