### ISSUE TITLE
Create a gae version

### ISSUE THREAD

**Issue by yes8080** [SystemRage/py-kms#59]
托管gae 美滋滋

**Comment by 6ec123321** [comment]
Write on english or close issue. Закрой нафиг свой запрос. Бухать меньше надо. Пиши на английском языке, я уважаю все народности и не нацист, но ты на международном ресурсе, и нечего тут борзеть.

**Comment by 6ec123321** [comment]
Закрывый или пиши на английском и точка.

**Comment by Simonmicro** [comment]
What exactly is the problem - on english please? @gobiking 

Otherwise please close the issue.
