### ISSUE TITLE
Office 2019!

### ISSUE THREAD

**Issue by TCB13** [SystemRage/py-kms#6]
Hello, first many thanks for the port it works flawlessly!

Is there any place where one might find the UUIDs required to make with work with Office 2019?

Thank you.

**Comment by SystemRage** [comment]
added SKUIDs, you can try if works but maybe it's not enough to activate Office 2019 because it needs right Pid Ranges for EPID randomization.
I'm working for a better update.

**Comment by ricktendo** [comment]
I just wanted to add that I was able to update Office 2019 just fine, even before the update. I don't know if this is because 2016 and 2019 are similar builds but I welcome your hard work maintaining/updating this awesome script.

**Comment by TCB13** [comment]
@SystemRage can you check my comment at https://github.com/SystemRage/py-kms/pull/7#issuecomment-433629731 ? I had to add those lines to `client.py` it seems to work, but I'm no expert.

**Comment by SystemRage** [comment]
Released py-kms_2018-11-15 that now supports Windows Server 2019 and Office 2019, fixing EPID generation.
However something like this: 
```elif config['mode'] == 'Office2019':
                config['RequiredClientCount'] = 5
                config['KMSProtocolMajorVersion'] = 6
                config['KMSProtocolMinorVersion'] = 0
                config['KMSClientLicenseStatus'] = 2
                config['KMSClientAppID'] = "0ff1ce15-a989-479d-af46-f275c6370663"
                config['KMSClientSkuID'] = "2ca2bf3f-949e-446a-82c7-e25a15ec78c4"
                config['KMSClientKMSCountedID'] = "617d9eb1-ef36-4f82-86e0-a65ae07b96c6"
```
but note that client.py is for testing, the real client is your PC with Windows/Office you want to activate.
