### ISSUE TITLE
Does it support visio?

### ISSUE THREAD

**Issue by xingcong2015** [SystemRage/py-kms#60]
Dose it support visio?

**Comment by xingcong2015** [comment]
I tried. Yes

**Comment by SwaggyZhang** [comment]
> I tried. Yes

Hello, I tried to activate visio Pro 2013 VOL, but I failed. The error code is 0xC004F074. Could you please help me solve it? Thank you.

**Comment by simonmicro** [comment]
As far as I see, no Visio does not work using KMS activation. Or at least not with this.

**Comment by Technetium1** [comment]
You're probably not using the right version of Visio if it doesn't work.
