### ISSUE TITLE
RDP server CALs

### ISSUE THREAD

**Issue by R030t1** [SystemRage/py-kms#68]
Does py-kms allow a server with the RDP role to log in non-admin users?

**Comment by t3r00t** [comment]
Idk but you can use an RDP Wrapper to bypass all windows limitations

**Comment by 6ec123321** [comment]
> Does py-kms allow a server with the RDP role to log in non-admin users?


A KMS server is a mechanism (service) for activating Microsoft products in a local network, for example Microsoft Office 2010-2019 (Standard, Enterprise) and Windows operating systems (7 and earlier).

Has nothing to do with RDP licenses

Please, R030t1, close Issue.

**Comment by R030t1** [comment]
No, it's a key management server, and features are gated behind those keys. The keys may or may not be just for the OS; see how py-kms will activate Office as well.

It *looks like* the RDP licensing server is separate from the key management server but I wasn't sure.

**Comment by 6ec123321** [comment]
I undestand you now, and what are you meen about RDP licensing, it is not project for you, we can't help you with RDP licensi, using left-keys fo this, and what about you, you can using left-keys too )), sorry me.

**Comment by SystemRage** [comment]
Some other info: 
https://github.com/Wind4/vlmcsd/issues/7
