### ISSUE TITLE
Address family for hostname not supported.

### ISSUE THREAD

**Issue by dual-oo** [SystemRage/py-kms#74]
Hi,

I've updated via git pull successfully. after restart my systemd service I got this error in the py-kms log.
`Wed, 08 Jul 2020 22:24:26 ERROR    Connection failed '0.0.0.0:1688': [Errno -9] Address family for hostname not supported. Exiting...`
Start Command is:
`/usr/bin/python3 /opt/py-kms/py-kms/pykms_Server.py -w RANDOM -F /var/log/py-kms.log -V INFO`

**Comment by Simonmicro** [comment]
Hi. Thats very strange! I recently implemented ipv6 support - it does listen to an other host address. On which system do you run it? And does it work, if you override the internal defaults by appending `:: 1688` to the start command?

**Comment by Simonmicro** [comment]
I tested it right now. Yes, the default param breaks with the ipv6 socket - I could reproduce and fix it with #76

**Comment by YarinAVI** [comment]
I have the same error....

**Comment by Simonmicro** [comment]
Okay, please test my patch and check if the problem persists: https://github.com/Simonmicro/py-kms/tree/patch-3
If yes, please wait until @SystemRage has time to accept my pull request.

**Comment by Simonmicro** [comment]
@dual-oo Fixed. Please close this issue now.
