### ISSUE TITLE
default address should not be 0.0.0.0 for IPV6

### ISSUE THREAD

**Issue by zhouhaiyangqq** [SystemRage/py-kms#78]
You add ipv6 support but doesn't change the default ip address configuration in pykms_Server.py.
Also the wiki must be modified too!!
Or it will throw a error message:
"Connection failed '0.0.0.0:1688': [Errno -9] Address family for hostname not supported!"
I have this problem when I use your code on debian 10 platform.
Please modify the default ip address to ipv6 format.

**Comment by Simonmicro** [comment]
Already reported in #74 and fixed in #76. You'll need to wait for @SystemRage to accept the PR.

**Comment by Simonmicro** [comment]
@zhouhaiyangqq Fixed. Please close this issue now...
