### ISSUE TITLE
UnknownTimeZoneError on Windows with pytz installed

### ISSUE THREAD

**Issue by Googulator** [SystemRage/py-kms#8]
On Windows, auto-detecting the time zone fails, as all 3 implemented methods are Linux-specific (Windows doesn't have /etc, and doesn't name time zones according to a "Continent/City" pattern). This causes a crash with UnknownTimeZoneError whenever a timestamp is logged.

There are two parts to this issue:

- On Windows, a different strategy is needed to find the time zone. See the "tzlocal" Python module on PyPi.
- When time zone determination fails, it shouldn't be treated as a fatal error - just print UTC timestamps, maybe with a warning, just like when pytz is missing.

**Comment by SystemRage** [comment]
Thanks.
Corrected with py-kms_2018-11-15.
