### ISSUE TITLE
error about getaddrinfo

### ISSUE THREAD

**Issue by sooluck** [SystemRage/py-kms#81]
the latest version could not run on my computer correctly,the log noticed that when the client connected,the server returned a error code 11001 and noticed that getaddrinfo failed.the test clinet also show "WinError 10049] 在其上下文中，该请求的地址无效。. "
I tested by this "python pykms_Server.py" and get no info in the log file.

**Comment by Simonmicro** [comment]
* Which OS are you running (host/client)?
* Did you started the py-kms to listen to ipv6 (`::`) - even if you don't use it?
* Are you running inside docker or not?

**Comment by SystemRage** [comment]
Yes. fixed with #86
