### ISSUE TITLE
[WIP] Create new wiki system

### ISSUE THREAD

**Issue by Simonmicro** [SystemRage/py-kms#82]
# Mission #
Port current wiki to readthedocs by using Sphinx and include it into the repo. Also extend it to demonstrate docker and include parts of the README (which is a little bit overfilled). Eventually restructure it (own section for keys, copy-paste for the windows commands...).

_This issue will stay here until it is fully implemented to be referenced by PRs._

**Any ideas / suggestions? Drop them in the comments!**

## Progress ##

- [x] New wiki
- [x] Reshoot screenshots with english terminal
- [x] Convert html tables to markdown tables, so the generated PDF handbook can display them
- [x] Merge docker/README.md into the docs
- [x] Add note about Dockerfiles after #93
- [x] Add contribution section

**Comment by Simonmicro** [comment]
Further TODOs

- [ ] reshoot screenshots with english terminal
- [ ] convert html tables to markdown tables, so the generated PDF handbook can display them

**Comment by Simonmicro** [comment]
- [ ] Merge docker/README.md into the docs

**Comment by Simonmicro** [comment]
@SystemRage I am thinking about adding a "Contributing" section to the docs - could you give me a list of your preferred doc/code styling you used?

**Comment by SystemRage** [comment]
let's say...
a) 8-space indentation without tabs.
b) docstrings as this:
```def test():
        """ This is single line docstring. """
        """ This is a
        """ multiline comment.
```
c) Wrap lines only if really long (it does not matter 79 chars PEP8)
for the rest a bit as it comes :)

**Comment by Simonmicro** [comment]
Just a little ping: This is still on my ToDo list and not abandoned. I'll work here again, when I have time...

**Comment by Simonmicro** [comment]
This took me a while - but it now done!

Transmission ended.
