### ISSUE TITLE
100% CPU usage...

### ISSUE THREAD

**Issue by lepoarro** [SystemRage/py-kms#83]
After updating Docker version to the latest build, I noticed that Docker environment was utilizing 100% of 1 CPU core of 4 given to my Docker environment under Unraid OS. First I thought that there was a problem with new py-kms Docker image and I tried to run py-kms in Debian VM to see if the python only version has the same problem and yes same issue exists. 

Running old python3 version:
![old](https://user-images.githubusercontent.com/68047844/88526044-1b054c00-d004-11ea-9f56-c7973b3edcf7.png)

Running new python3 version:
![new](https://user-images.githubusercontent.com/68047844/88526125-32443980-d004-11ea-9d2f-bf44d1a590b2.png)

Docker environment:
![docker](https://user-images.githubusercontent.com/68047844/88527428-e98d8000-d005-11ea-80e0-f65b5fa00c59.png)

Hope this information helps!

**Comment by Simonmicro** [comment]
Okay, that is strange. Well, we've had this before https://github.com/SystemRage/py-kms/issues/38 - and then fixed. Additionally I had fixed this in #51 for docker. But you are right. It is here again. I can reproduce this and will take a look further into it.

**Comment by lepoarro** [comment]
It seems `Fix for `#58 messes up the CPU usage under Linux. I rolled back the fix in `pykms_Server.py` file and the CPU usage went back to normal. I'm not the python expert, so can't really understand what is the real problem, just tried to roll back latest fixes to see if something changes and it did.

**Comment by SystemRage** [comment]
i don't know why, but he didn't like 
`selector.register(fileobj = self.w_service.fileno(), events = selectors.EVENT_WRITE)`
