### ISSUE TITLE
location of SQLite database file

### ISSUE THREAD

**Issue by tuaris** [SystemRage/py-kms#88]
Where does the database file get created?  Can it be changed through a CLI argument?

**Comment by SystemRage** [comment]
`python3 pykms_Server.py -s`
creates _pykms_database.db_ in the same path of pykms_Server.py file.
`python3 pykms_Server.py -s /custom/path/yourdatabase.db`
creates _yourdatabase.db_ under _/custom/path/_

**Comment by Simonmicro** [comment]
@tuaris I guess this can be closed now?

**Comment by tuaris** [comment]
@Simonmicro yep.  Thanks.
