### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by tuaris** [SystemRage/py-kms#89]
I've made a FreeBSD port: https://github.com/tuaris/freebsd-py-kms

I doubt it will get included by default in the ports tree, but it's easy to build your own local package if you don't use Poureire

```
git clone https://github.com/tuaris/freebsd-py-kms.git
cd freebsd-py-kms
make package
```

In order to get this working I had to patch a few things (all handled by the port).

- Related to issue #88, change the location of the sqlite database file
- in `pykms_Server.py` I had to change the location of the state file created by etrigan (`pykms_config.pickle`).

**Comment by Simonmicro** [comment]
What exactly did you needed to modify? Maybe we could merge it into the master - if the changes do not break the default instance?! :smile:

**Comment by SystemRage** [comment]
i created cli argument for database path, see #88.
i don't know if is useful to create a cli for pykms_config.pickle, it's only a temp file to remember parameters.

**Comment by 6ec123321** [comment]
It's pointless to use FreeBSD in 2020)

**Comment by 6ec123321** [comment]
I'm like a chines: Ты для чего сделал порт freebsd, вот кто его будет использовать, блин, все компании перешли на линукс, походу ты не в курсе, кубернейтс пора бы уже изучить, я пока не изучил.

**Comment by Prianik** [comment]
чего за всех то говорить. Использовали и используют

**Comment by 6ec123321** [comment]
Блин, что за тупой народ, прямо злость взяла, ты сделал не зная зачем для чего то, чем не будут пользоваться, лучше бы make file допилил до нужного состояния, автор программы py-kms своё детище доделывает, как службу теперь запускать надо, переделайте start.sh ну не тупите, хватит делать порты для FreeBSD. Да, я зол, когда не туда копают, думают что это всем надо, а может это только вашей жопе надо?


Damn, what kind of stupid people, you just took anger, you did not knowing why for what something that they will not use, it would be better to finish the make file to the desired state, the author of the py-kms program finishes his creation, how to start the service now, remake start.sh don't be stupid, it's enough to make ports for FreeBSD. Yes, I'm angry when they dig in the wrong place, they think that everyone needs it, but maybe it's just your ass who needs it?

**Comment by 6ec123321** [comment]
Do not use FreeBSD in production, please, do not use, if you can't make kernel. 2020 year - time for LINUX and Torvalds. If you not with us, go to ass.

**Comment by 6ec123321** [comment]
You don't known is for what FreeBSD is needed, you are stupid, and i'm drinking in this time, sorry. Docker on freebsd - you are crazy )))

**Comment by 6ec123321** [comment]
Close this and go ahead), teaching self.

Закрой и иди нафиг учись

**Comment by 6ec123321** [comment]
You write pfsens - stupid, who can use pfsens, one, two, three - nothing. I'm not using pfsens, only FreeBSD fimware fo routers

**Comment by 6ec123321** [comment]
We are 12 hours apart, so consider your request.

**Comment by Simonmicro** [comment]
@6ec123321 WTF dude? What is your point? We have someone here, which want to use FreeBSD. Fine. He also modified code so it works on his system (apparently that was not needed, because as @SystemRage already pointed out we have a parameter for that). I don't see any reason here to rant about pfsense (which I have never used, but may will in the future, because an own open-sourced router sounds good to me) nor I see any reason here to tell someone to "go to ass" nor to tell someone he is stupid. Please, when you drink you should probably not write stuff (I must admit drunken code is some kind of... interesting)... :no_mouth:

**Comment by 6ec123321** [comment]
All of i want to say is meen: FreeBSD is Depricated for all Eropen project with security black-holes --- that you understand man ?

**Comment by 6ec123321** [comment]
Russian FSB chek and black-listed FreeBSd for infiniti time ), black-hole detected in my country, we can make best weapon, you understand this "black-houle", i'm not understand what it meens, but they tell me "never using FreeBSD".

**Comment by Simonmicro** [comment]
> Russian FSB chek and black-listed FreeBSd for infiniti time ), black-hole detected in my country, we can make best weapon, you understand this "black-houle", i'm not understand what it meens, but they tell me "never using FreeBSD".

Ah, got it now! In that case it is may not the best idea to use it, BUT i think it greatly depends on the usage scenario: After all that system uses the Linux Kernel, which means basic functionality like the good old firewall works there too. Also when you are not exposing "badly programmed code", it should be fine? But imho you should not use any flawed systems in the open, but this is an other topic. Not meant for this issue 😁

**Comment by tuaris** [comment]
> 
> 
> i created cli argument for database path, see #88.
> i don't know if is useful to create a cli for pykms_config.pickle, it's only a temp file to remember parameters.

@SystemRage thanks for handling #88.  

In regards to `pykms_config.pickle`, the main issue is that it's created in the same directory where pykms is running.  On Unix/Linux systems that directory my not be writable.  Maybe it might make more sense to detect the OS's temp directory, (I think Python has that ability to do that via [tempfile](https://docs.python.org/3/library/tempfile.html)) and put the file in their?.

**Comment by tuaris** [comment]
I hate to continue adding to the off topic conversation.  I am not aware of anything in regards to FreeBSD being a security issue or being on any blacklists.  It is frequently used in critical systems throughout the world by large companies and governments.  Anyway, I won't continue to hijack this thread and ask that you do the same.  Thanks all.
