### ISSUE TITLE
ARM Docker image

### ISSUE THREAD

**Issue by UnpilotedRebuilt1** [SystemRage/py-kms#92]
Hey thanks for making this app! I needed something that would work offline for my testing machine. Please could an ARM image be made for Docker? I'd love to pop this app on my Raspberry Pi using docker.

**Comment by Simonmicro** [comment]
Hmm, interesting idea - I already gave it a thought but dismissed it prematurely. I'll take a look into that in the next days.

Here some references (or more some of my notes I already found):
* https://hub.docker.com/r/ckulka/multi-arch-example
* https://www.trion.de/news/2019/10/14/docker-multi-arch-dockerhub.html
* https://www.henry.wang/2019/12/05/arm-dockerhub.html

**Comment by Simonmicro** [comment]
Okay, what _exact_ architecture do you need? Could you may post the output of the `uname -a` and `uname -m` command?

**Comment by UnpilotedRebuilt1** [comment]
> Okay, what _exact_ architecture do you need? Could you may post the output of the `uname -a` and `uname -m` command?

For me personally I would need ARMv7 32-bit however to support basically all Raspberry Pi models I'd use ARMv6 32-bit if possible

**Comment by Simonmicro** [comment]
Enjoy #93! :grin:

**Comment by UnpilotedRebuilt1** [comment]
> Enjoy #93! 😁
> It supports ANY current Raspberry Pi...

Thanks! Very much appreciated

**Comment by 6ec123321** [comment]
Thanks! Well done. When my laptop breaks down, now i can buy new raspberry pi4 with 8 GB on ARM CPU - Thanks!

**Comment by Simonmicro** [comment]
Well, @SystemRage when will you have some time to review and merge #93 ? I know you are a busy man, so is there any way how I can help you out?

**Comment by Simonmicro** [comment]
@UnpilotedRebuilt1 Soo, it is done! The build has been completed successfully and now the `minimal` and `latest` tag are available for multiple architectures. Enjoy them!

_May leave a feedback here and close this issue now :partying_face: _
