### ISSUE TITLE
IOT Enterprise

### ISSUE THREAD

**Issue by HL52840** [SystemRage/py-kms#99]
Does this work on Windows 10 IOT Enterprise?

**Comment by Simonmicro** [comment]
When you have a GVLK key... Yes? Take a look at: https://py-kms.readthedocs.io/en/latest/Keys.html#windows-10 Maybe you need to find a key for your version first (make sure to leave a copy of it here, when you've got it)...

**Comment by HL52840** [comment]
There seems to be no GVLK key. I can source a key, but I don't know if pykms can even recognize the version.

**Comment by HL52840** [comment]
It doesn't seem to be on the supported list.

**Comment by SystemRage** [comment]
IoT Enterprise not support KMS activation.
You can opt  for Windows 10 Enterprise LTSC/LTSB,
which is essentially the same and can be KMS activated.

**Comment by HL52840** [comment]
Ok. Thanks for letting me know.
